# string: Excel文件所在目録，路徑分隔符需要用/，留空表示當前目録
xl_dir = ''
# list string: excel文件後綴。默認忽略以 ~$, __ 開頭的文件
file_exts = ['xlsx', 'xls', 'xlsm']
# bool: 是否在目録下遞歸搜尋excel文件
recursive_xl_files = false

# string: Excel文件中需導出的sheet前綴
sheet_name_prefix = '#'
# string: Excel的sheet區域標記符號，只導出區域內的內容
bound_tag = '#'

# list string: Excel中定義各使用類型的名稱，可多個
int_name = ['int', 'i', 'integer']
float_name = ['float', 'f']
bool_name = ['bool', 'b', 'boolean']
str_name = ['str', 's', 'string']
intlist_name = ['intlist', 'li', 'il', 'int[]']
floatlist_name = ['floatlist', 'lf', 'fl', 'float[]']
boollist_name = ['boollist', 'lb', 'bl', 'bool[]']
strlist_name = ['strlist', 'stringlist', 'ls', 'sl', 'string[]']
dict_name = ['dict', 'dic', 'json']
dictlist_name = ['dictlist', 'diclist', 'dic[]']

# list string: Excel配置中不使用的行與列標識，被註釋則不會導出
note_signs = ['//', '--']

# int: 基礎數據格式
# 0-二維列表 [['key','hp'...],[1,30...],[2,50...]...]
# 1-條目字典列表 [{'key':1,'hp':30...},{'key':2,'hp':50...}...]
# 2-key嵌套字典 {1:{'hp':30...},2:{'hp':50...}...}
base_data_style = 2

# bool: 是否緩存數據，緩存以pickle形式存儲
cache_data = true
# string: 緩存數據存儲的文件名
cache_dir = '__output/__xldata.pkl'

# string: 輸出模板
    # csv: 普通csv格式
    # json: 普通json格式
    # unity: 默認unity配置格式，同時輸出代碼
    # godot: 默認godot配置格式，同時輸出代碼
output_template = 'godot'
# string: 輸出文件的目録，路徑分隔符需要用/
output_dir = '__output/'
# string: 輸出文件後綴名（非一個大文件時）
output_ext = 'txt'
# bool: 輸出一個大文件，還是分別輸出
output_in_one = true
# string: 輸出至一個大文件的文件名
output_in_one_fn = 'raw_data.gd'
# string: 輸出文件頭部內容（中文會亂碼）
output_file_header = '## Excel Config Raw Data\nclass_name RawData extends Object\n\n'
# string: 輸出文件尾部內容（中文會亂碼）
output_file_tail = '# Auto generated by gamefang.xl_converter'

# list string: 完成後額外執行的腳本路徑列表
done_scripts = [
    'trans_gen.py',
]